pygments: true
permalink: /:categories/:year/:month/:day/:title 
markdown: kramdown
paginate: 2
paginate_files: ['index.html', 'blog', 'authors/kartben/index.html']

authors:
  kartben:
    username: kartben
    display_name: Benjamin Cabé
    gravatar: 6a9709b2e69ab3bb3bf786acb6323366
    web: http://blog.benjamin-cabe.com/
    twitter: kartben
    github: kartben
    gplus: 112837264176638481892
  sebz:
    username: sebz
    display_name: Sébastien Moran
    gravatar: 6e0f84a522cf43154299fdf2798c659d
    twitter: sebz
    github: sebz
  gaetan:
    username: gaetan
    display_name: Gaétan Morice
    gravatar: 2d6cc32e710c17a641a5c87266322438
    twitter: gmorice
    github: gaetanmorice
  vrmvrm:
    username: vrmvrm
    display_name: Julien Vermillard
    gravatar: cf8a296ad8ebdf41f76d75f50470ecf0
    twitter: vrmvrm
    github: jvermillard
  dsciamma:
    username: dsciamma
    display_name: David Sciamma
    gravatar:  14d36b6a2ea4a6e0271559aba29b9326
    twitter: dsciamma
  thibs:
    username: thibs
    display_name: Thibault Cantegrel
    gravatar: a9dc4900710f1892704aa76992bd2fcb
  kinfoo:
    username: kinfoo
    display_name: Kévin Kin-Foo
    gravatar: 3aba2f30d036a8e61c02f78d0a6ce083
  lbarthelemy:
    username: lbarthelemy
    display_name: Laurent Barthélémy
    gravatar: 723dac40c3f64f1cd87ef3ced1f4a9b4
  kinfoo:
    username: phtrivier
    display_name: Pierre-Henri Trivier
    gravatar: b8efdf0b5e92a9e758386990822f0be8
